### ISSUE TITLE
npm module (TypeScript)

### ISSUE THREAD

**Issue by Tobbe** [jop-io/kontonummer.js#13]
In modern web projects it would be easier to use this project if it was available on npm. It would also be nice if it had TypeScript bindings as more and more big projects are moving to TS.

Is this something you would be interested in? Or should I create a fork for that?

**Comment by jop-io** [comment]
Jag håller med om att detta vore bra, men har saknar tid att ägna åt detta.

Du har fått en inbjudan som collaborator - tolka inbjudan som att du är välkommen att göra lite som du vill :-)
