### ISSUE TITLE
Kontonummer.js fungerar inte i senaste Firefox, Safari eller Edge.

### ISSUE THREAD

**Issue by joiglifberg** [jop-io/kontonummer.js#4]
Ingen av ovanstående nämnda webbläsare stöder _negative lookbehind_ som används här https://github.com/jop-io/kontonummer.js/blob/master/kontonummer.js#L145.

**Comment by PaddySe** [comment]
Det verkar som om negative lookbehinds stöds enbart i ECMA2018, och det är bara Chrome som har stöd för det än så länge.

**Comment by christianz** [comment]
@jop-io Would it be possible to publish your test data for the Nordea account numbers, so someone could try to find a workaround for this?

**Comment by jop-io** [comment]
Ändrade till negative look ahead, vilket har lite bättre stöd.

https://github.com/jop-io/kontonummer.js/commit/292f0323504dc8b90762c187f3150e0e21900a30
