### ISSUE TITLE
Validering av Swedbank bankkontonummer

### ISSUE THREAD

**Issue by noordh** [jop-io/kontonummer.js#5]
Se den här texten som kommer från http://clearingnummer.info/. ”Swedbank och fristående Sparbanker. Det förekommer att Swedbank har en femte siffra i clearingnummer som börjar på 8, t ex 8327-9. **Den femte siffran ska inte registreras.** När du gör en överföring till Swedbank ska kontonummer som börjar på 8 alltid bestå av sammanlagt fjorton siffror. Om det innehåller färre siffror ska du fylla ut med nollor mellan clearingnumret (de första fyra siffrorna) och resterande siffror i kontonumret. 8000-8999 10”
 
Kontonumret som hade problem ser ut så här (korrekt clearing nummer men fejkat kontonummer, men med samma mängd siffror och skrivsätt): 

8304-8 12345678-2
 
Ska man följa texten ovan så skall man skriva in kontonumret på detta vis: 

83040123456782

men det går inte igenom valideringen, men om man anger en 5:e siffra ändå på clearingnumret så går det igenom. (Det behöver inte vara 8 som i detta fall utan vilken 5:e siffra som helst verkar gå bra) 

8304 8 0 123456782

**Comment by jop-io** [comment]
@noordh Denna information stämmer inte överens med instruktionerna som ges för dataclearingen av [Bankgriot](https://www.bankgirot.se/globalassets/dokument/anvandarmanualer/bankernaskontonummeruppbyggnad_anvandarmanual_sv.pdf) och inte heller med den information som tillhandahålls av [Swedbank](https://hjalp.swedbank.se/sidhjalp-internetbanken-privat/ordlista/c-h/index.htm#Clearingnummer).

Provar man att lägga till och överföra pengar till ett kontonummer som är formaterat på detta sätt får man både på Swedbanks hemsida och i deras app ett meddelande om att kontonumret är felaktigt.

Således ingen åtgärd på detta.
