### ISSUE TITLE
Swedbank igen

### ISSUE THREAD

**Issue by gubbcarl** [jop-io/kontonummer.js#6]
Hej

Jag tror jag har hittat ett litet fel i Swedbank-valideringen med clearing som startar med 8.

Regex-raden för Swedbank med clearing som startar på 8 är:
**regex: /^8[0-9]{10,14}$/ // Clearingnr 5 siffror, räkningsnr 7-10 siffror**

Borde inte quantifier-rangen vara {11,14}? Nu släpper den igenom nummer med 5 siffror som clearing och 6 siffror som räkningsnr.

**Comment by Tobbe** [comment]
@gubbcarl Jag tror definitivt du har rätt. Jag hittar faktiskt inte ens något belägg för att kontonumret skulle vara något annat än totalt 15 siffror långt. 5 siffror i clearingnumret, 9 siffror + 1 kontrollsiffra i kontonumret. Swedbank själva skriver att det alltid är 15 siffror: https://www.swedbank.se/privat/kort-och-betala/konton-for-in-och-utbetalningar/clearingnummer.html

Så jag tror regexet kan förenklas till `/^8[0-9]{14}$/`

**Comment by jop-io** [comment]
@Tobbe @gubbcarl På Svenska Bankföreningens sida står följande:

> Typ 2 är den äldre kontotypen och där ingår inte clearin​gnumret i kontot. Detta konto kan bestå av allt från 5 till 11 siffor. Det är framför allt Handelsbanken, Nordea och Swedbank, inklusive de fristående sparbankerna, som har byggt upp sin kontostruktur på detta sätt. Bankföreningen strävar dock efter en ökad standardisering på den svenska marknaden och tillåter sedan drygt 15 år tillbaka endast kontotyp 1 för nya banker.

Jag har tidigare varit i kontakt med både Svenska bankföreningen och Swedbank. Efter att ha fått information från dem (i synnerhet Swedbank), har jag skrivit den nuvarande regexp:en och den är giltig. Kommentaren bör dock uppdateras till `// Clearingnr 5 siffror, räkningsnr 6-10 siffror`, alternativt tas bort helt.

Om jag minns informationen rätt nu mitt i natten så finns det kvar gamla kontonummer från ihopslagningen av Sparbakerna och Föreningsbaken, vilka då fick clearingserien som börjar med 8 och som kan ha allt från 6-10 siffror som räkningsnummer.

**Comment by Tobbe** [comment]
@jop-io Tack för förtydligandet.

Jag hittade själv detta
> Ofta räcker det att ange nio siffror för de kontonummer som börjar 043 xxx xxx - x. Dvs 43 xxx xxx - x
https://www.halsinglandssparbank.se/share/8129-fragments/bankinformation/clearingnummer.html

Så (i alla fall nu för tiden) har alla konton 10 siffror, men i de fallen de första siffrorna är 0 kan de uteslutas. Vilket stödjer din kommentar ovan. Men med anledning av ditt citat undrar jag om Handelsbankens regex också ska uppdateras till att stödja olika antal siffror i kontonumret. Vad har du för tanke där?

Jag röstar för att kommentaren i koden tas bort.

**Comment by jop-io** [comment]
@Tobbe Enligt Lars Rutborg på Svenska bankförening har både Swedbank och Handelsbanken konton vars räkningsnummer kan inledas med "0", och då ska den inte uteslutas.

Från Handelsbanken har jag inte fått något svar på frågan kring om deras räkningsnummer kan ha en varierande längd, utan i stället gått på det Bankgirot definierar som en korrekt längd för dataclearingen (9 siffror). Se kommentar 2 för konton av typ 2.

Detta tordes också vara det korrekta svaret - annars skulle det vara svårt att göra clearingen mellan Handelsbanken och andra banker :-)

**Comment by Tobbe** [comment]
Perfekt. Då återstår det bara att plocka bort kommentaren :) Om du inte
hinner före så kommer en PR i morgon

**Comment by Tobbe** [comment]
Kommentar uppdaterad i PR #10. Jag valde att behålla kommentaren i alla fall, men uppdaterade den så klart :)
